### ISSUE TITLE
Error when trying my script

### ISSUE THREAD

**Issue by kaholita** [george-lim/kijiji-bot#1]
Hi! I got this error showing and I'm not sure if it's due to the special characters used 
in the name of my Location.
Could you help me figure that out please ?

I'm located in Montr**é**al, Qu**é**bec

Jean.

_____

> python repost.py
Image upload success on try #1
Image upload success on try #1
WARNING:root:Failed to post ad: PC Case Antec
Traceback (most recent call last):
  File "C:\Users\jean_\OneDrive\Documents\kijiji repost\repost.py", line 12, in <module>
    bot.repost_ads(ads_path, is_using_alternate_ads, post_delay_seconds)
  File "C:\Users\jean_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kijiji_bot\__init__.py", line 135, in repost_ads
    raise KijijiBotRepostException(exceptions)
kijiji_bot.KijijiBotRepostException: PC Case Antec:
Could not post ad. (dump available)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jean_\OneDrive\Documents\kijiji repost\repost.py", line 14, in <module>
    exception.dump()
  File "C:\Users\myname\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kijiji_bot\__init__.py", line 54, in dump
    [exception.dump() for exception in self.exceptions]
  File "C:\Users\jean_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kijiji_bot\__init__.py", line 54, in <listcomp>
    [exception.dump() for exception in self.exceptions]
  File "C:\Users\jean_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\kijiji_bot\__init__.py", line 43, in dump
    dump_path.write_text(self.html_dump)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1275, in write_text
    return f.write(data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45126-45127: character maps to <undefined>

**Comment by george-lim** [comment]
This appears to be an issue with the Kijiji API that Kijiji Bot uses. Please submit this issue to [Kijiji-repost-headless](https://github.com/ArthurG/Kijiji-Repost-Headless).

**Comment by george-lim** [comment]
Investigating this further, while I cannot solve the original exception (you should still submit this issue to the other repository), I believe I can solve the second one. Can you tell me the title of the ad that failed?
