### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ads'

### ISSUE THREAD

**Issue by hussein-esmail7** [george-lim/kijiji-bot#3]
I'm having this issue where it cannot locate the 'ads' folder.
Here is the full output of the code:
```
Traceback (most recent call last):
  File "kijiji_repost.py", line 17, in <module>
    bot.repost_ads(ads_path, is_using_alternate_ads, post_delay_seconds)
  File "/Users/hussein/Library/Python/3.8/lib/python/site-packages/kijiji_bot/__init__.py", line 71, in repost_ads
    for ad_file_path in self.get_ad_file_paths(ads_path):
  File "/Users/hussein/Library/Python/3.8/lib/python/site-packages/kijiji_bot/__init__.py", line 63, in get_ad_file_paths
    return reduce(lambda x, y: x + self.get_ad_file_paths(y), path.iterdir(), [])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1113, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'ads'
```

I do acknowledge that there is no 'ads' folder, and I'm not sure how that's supposed to be created. I'm trying to repost the ads that are on my account and that are already posted.

**Comment by george-lim** [comment]
That's not how this bot works unfortunately. If you take a look at the Kijiji-Repost-Headless repo (which this bot is based on) it allows you to create ads locally on your computer, which then get reposted. You must follow the format of their ad.

To clarify, this app does not source ads that already exist on Kijiji. It simply reposts ads written on your computer.
